server.port=8080
spring.config.import=optional:file:.env
spring.application.name=crudapi
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs

# Database Configuration (Reads from Environment Variables)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/taskdb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Initialize Database from schema.sql automatically
spring.sql.init.mode=always