spring.application.name=auth-service
server.port=${PORT:3000}
supabase.url=${SUPABASE_URL:https://nxbnccbifiglzzojgrec.supabase.co}
supabase.key=${SUPABASE_KEY:sb_publishable_q8T4Iv_1vR1CMBNYRey-7Q_xilRM_xI}
springdoc.swagger-ui.path=/docs